In [1]:
#Step1:Import packages,functions,and classes
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
#Step2:Get data
x=np.arange(10).reshape(-1,1)
y=np.array([0,1,0,0,1,1,1,1,1,1])
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 0 0 1 1 1 1 1 1]


In [5]:
#Step3:Create a model and train it
model=LogisticRegression(solver='liblinear',C=10.0,random_state=0)
model.fit(x,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [8]:
#Step4:Evaluate the model
p_pred=model.predict_proba(x)
y_pred=model.predict(x)
score=model.score(x,y)
conf_m=confusion_matrix(y,y_pred)
report=classification_report(y,y_pred)

In [9]:
print('x:',x,sep='\n')
print('y:',y,sep='\n',end='\n\n')
            
            

x:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y:
[0 1 0 0 1 1 1 1 1 1]



In [11]:
print('intercept:',model.intercept_)
print('coef:',model.coef_,end='\n\n')

intercept: [-1.51632619]
coef: [[0.703457]]



In [12]:
print('y_actual:',y)
print('y_pred:',y_pred)

y_actual: [0 1 0 0 1 1 1 1 1 1]
y_pred: [0 0 0 1 1 1 1 1 1 1]


In [13]:
print('conf_m:',conf_m,sep='\n',end='\n\n')


conf_m:
[[2 1]
 [1 6]]



In [14]:
print('report:',report,sep='\n')

report:
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10

